### ISSUE TITLE
可以发个邀请码吗

### ISSUE THREAD

**Issue by codesbull** [laomms/MSReceiver#1]
关于send key的
my.cherish@outlook.com

**Comment by youkestar** [comment]
可以给我一个邀请码吗？
youkestar@gmail.com

**Comment by danhdat0001** [comment]
关于send key的
onlyg1h1@gmail.com

**Comment by majudu** [comment]
能给个邀请码吗？

**Comment by SmozX** [comment]
能给个邀请码吗？
1723471165@qq.com
谢谢

**Comment by aishiduyao** [comment]
能发给我一个邀请码吗？谢谢2496148116@qq.com

**Comment by somebody2333** [comment]
可以发个邀请码吗2319099045@qq.com谢谢

**Comment by jbdqs** [comment]
能给我邀请码吗，我想通过发送器发送密钥，避免密钥不必要的浪费，谢谢2378618968@qq.com

**Comment by hyx520** [comment]
可以给我个邀请码吗？QQ：3210683450

**Comment by hyx520** [comment]
谢谢

**Comment by hyx520** [comment]
大神，我想问问怎么拿邀请码？

**Comment by wolfxiaojie** [comment]
可以给一个邀请码吗wolfxiaojie@outlook.com

**Comment by Tanjing010726** [comment]
可以给个邀请码吗17631152014@163.com

**Comment by sam271118** [comment]
可以给个邀请码吗 du.sock@gmail.com

**Comment by hudada1234** [comment]
可以给我个邀请码吗？QQ：350543117

**Comment by hudada1234** [comment]
可以给我个邀请码吗？350543117@qq.com谢谢！

**Comment by 359386909** [comment]
能给我邀请码吗，我想通过发送器发送密钥，避免密钥本身的浪费，谢谢大神359386909@qq.com

**Comment by laomms** [comment]
已停止开发及维护.
