### ISSUE TITLE
如何注册

### ISSUE THREAD

**Issue by haihang5000** [laomms/MSReceiver#12]
请问一下如何注册的？邀请码是如何得到？如可以的话请发一下到邮箱3112982@qq.com.
感谢！你的软件很有趣。希望能试用。

**Comment by laomms** [comment]
服务端可以免账号登陆发送密钥给客户端。
需要其他功能下载[git仓里另一款工具](https://github.com/laomms/KmsTool/releases)，功能是一样的。
